### ISSUE TITLE
Changing Full name used in emails sent

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#13] opened 2022-03-03 19:37 UTC
Tried to change NAME, which one sees in My account and it didnt change the sender's name in emails sent.

I had to explain that's the profile name... Not the sender, which is inside email settings.

It seems, however, this is a bug and changing in my account should change that primary account's name, at least.

See  name in webmail [#486010]

Thanks.

**Comment by polarismail** [comment] 2022-03-04 17:42
This is not a bug, it's expected behavior.

An account can have multiple e-mail accounts and it would be unexpected to change all of them.

If you want a full name change we recommend that you change the name in the Admin Panel which will propagate everywhere

**Comment by flaviozluca** [comment] 2022-03-04 18:59
I see, but it leads user to error.

You're the one that said it was a bug. See name in webmail #486010. You said "this one is actually, a bug, please add to github issues"

Can't we improved this in any way? Examples of ideas:

- change the name if just 1 account (most cases)
- tell them textually "this is the profile name, to change sender, click here or go to this place - email accounts, etc"
- see if GO can improve this

**Comment by polarismail** [comment] 2022-03-04 19:02
I thought you meant it was not changing the name when doing it from the Admin Panel, not GO.

we have no control over this, this is 100% GO. 

If you want to change this behavior, you could open a feature request with them

**Comment by flaviozluca** [comment] 2022-03-07 17:02
Thanks. See if Ok, please. https://github.com/Intermesh/groupoffice/discussions/814

**Comment by polarismail** [comment] 2022-03-16 09:47
looks good, will close the issue here

**Closed as completed by polarismail** 2022-03-16 09:47 UTC
